services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
  redis:
    image: redis:latest
    container_name: redis_container
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx_container
    depends_on:
      - api
      - client
    ports:
      - "3050:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: api_container
    volumes:
      - /server/node_modules
      - ./server:/server
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client_container
    volumes:
      - /client/node_modules
      - ./client:/client
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    container_name: worker_container
    volumes:
      - /worker/node_modules
      - ./worker:/worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
