# name: Deploy Frontend
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v3
#       - name: Login to Docker
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build Docker Container
#         run: docker build -t sstonn/react-test -f Dockerfile.dev .
#       - name: Run test for Docker Container
#         run: docker run -e CI=true sstonn/react-test npm test

#       - name: Generate deployment package
#         run: zip -r deploy.zip . -x '*.git*'

#       - name: Deploy to EB
#         uses: einaregilsson/beanstalk-deploy@v22
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           application_name: docker-react-app
#           environment_name: Docker-react-app-env
#           existing_bucket_name: elasticbeanstalk-ap-southeast-2-339712796583
#           region: ap-southeast-2
#           version_label: ${{ github.sha }}
#           deployment_package: deploy.zip

name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Test Container  
        run: docker build -t sstonn/react-test -f ./client/Dockerfile.dev ./client
      - name: Run test for Docker Container
        run: docker run -e CI=true sstonn/react-test npm test

      - name: Build Docker Production Container
        run: docker build -t sstonn/multi-client ./client
      - name: Build Docker Production Nginx Container
        run: docker build -t sstonn/multi-nginx ./nginx
      - name: Build Docker Production Server Container
        run: docker build -t sstonn/multi-server ./server
      - name: Build Docker Production Worker Container
        run: docker build -t sstonn/multi-worker ./worker

      - name: Push Docker Production Containers to Docker Hub
        run: docker push sstonn/multi-client
      - name: Push Docker Production Nginx Container to Docker Hub
        run: docker push sstonn/multi-nginx
      - name: Push Docker Production Server Container to Docker Hub
        run: docker push sstonn/multi-server
      - name: Push Docker Production Worker Container to Docker Hub
        run: docker push sstonn/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multid-docker
          environment_name: Multid-docker-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-339712796583
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

